[supervisord]
nodaemon=true

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true

[program:php-fpm]
command=php-fpm8.3 --nodaemonize
autostart=true
autorestart=true

[program:smtp]
command=php /var/www/artisan smtp:serve
autostart=true
autorestart=true
stdout_logfile=/var/log/smtp.log
stderr_logfile=/var/log/smtp.log
stdout_logfile_maxbytes=1MB
stderr_logfile_maxbytes=1MB

[program:reverb]
command=php /var/www/artisan reverb:start --port=6001
autostart=true
autorestart=true
stdout_logfile=/var/log/reverb.log
stderr_logfile=/var/log/reverb.log
stdout_logfile_maxbytes=1MB
stderr_logfile_maxbytes=1MB

[program:scheduler]
command=sh -c "while true; do php /var/www/artisan schedule:run --no-interaction >> /var/log/scheduler.log 2>&1; sleep 60; done"
autostart=true
autorestart=true
stdout_logfile=/var/log/scheduler.log
stderr_logfile=/var/log/scheduler.log
stdout_logfile_maxbytes=1MB
stderr_logfile_maxbytes=1MB
